# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aad37879044173adfbb54899245d2ef8b2a7660d0cbc4e610b05d09d852b222585428b79101b6d40941ac67a6a2fa97e23959efd8c8fe758c02e1fe13acd3c26

test:
  secret_key_base: 40884d8d635d7f865834a389f701c1790fa9d0d77912def6b76155ba1f7dacf66587203128945c6bd9e79f56045017e3a5a8b5c2af1e4f048a50ef45541066e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
